# Generated by Django 6.0.6 on 2026-06-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraUebung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(blank=True, max_length=50)),
                ('dauer_minuten', models.IntegerField(blank=True, null=True)),
                ('distanz_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notiz', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SatzErgebnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uebung_name', models.CharField(blank=True, max_length=200)),
                ('satz_nummer', models.IntegerField(default=1)),
                ('wiederholungen', models.IntegerField(default=0)),
                ('gewicht', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('gewicht_erhoehen', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['satz_nummer', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen', models.BooleanField(default=False)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('notiz', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='Trainingsplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('gewicht_steigerung', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Uebung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('saetze', models.JSONField(default=list)),
                ('hinweis', models.TextField(blank=True)),
                ('gewicht', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('reihenfolge', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['reihenfolge', 'id'],
            },
        ),
    ]
