# Generated by Django 6.0.6 on 2026-06-12 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='satzergebnis',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satz_ergebnisse', to='training.trainingsession'),
        ),
        migrations.AddField(
            model_name='extrauebung',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_uebungen', to='training.trainingsession'),
        ),
        migrations.AddField(
            model_name='trainingsplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingspläne', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='trainingsplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.trainingsplan'),
        ),
        migrations.AddField(
            model_name='uebung',
            name='trainingsplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebungen', to='training.trainingsplan'),
        ),
        migrations.AddField(
            model_name='uebung',
            name='vorgaenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nachfolger', to='training.uebung'),
        ),
        migrations.AddField(
            model_name='satzergebnis',
            name='uebung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ergebnisse', to='training.uebung'),
        ),
    ]
