#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Running database migrations..."
python manage.py migrate --noinput

echo "Collecting static files..."
python manage.py collectstatic --noinput

echo "Django is ready"

exec "$@"
